### PR TITLE
Flashbake3

### PR DESCRIPTION
**Pull request by ianpaul**
This pull request ports Flashbake to Python 3. There are more improvements to be made such as switching to more Python 3-like code, adding HTTPError messages to connectable plugins that don't have them, and other improvements. These, I think, would be better handled as smaller pull requests. This is already large, and the important thing is it works.

This branch has been tested on WSL on Windows 10, macOS Catalina, Crostini (Chrome OS), Ubuntu 20.04 (on VirtualBox) and Ubuntu 21.04. They all worked using Python 3.7 or later. I'd suggest bumping the release number with this to 0.30 to make it easier to understand where Python 3 versions start.

This branch has removed `growl.py`, `identica.py`, and `scrivener.py`. Scrivener will return at a later date (see thread). The Music plugin has lost Banshee as that project is more or less over. In its place there's a Rhythmbox option for Ubuntu users, which is now the default on that platform. The Rhythmbox option currently scans the XML database and returns songs played in the last 10 minutes. If a legacy Banshee user wants to port that class to Python 3 I'd be happy to help them do that.

I've also added two versions of iTunes for Mac users. Older Mac users should use `itunes.py` and `current_track_itunes.scpt`, while Catalina and up can use the Music class inside `music.py` and the regular `current_track.scpt`.  I was unable to test `itunes.py` but it should work as it's based on `music.py` for Python 3. The other thing is `current_track.scpt` for both versions now has to live inside a Mac user's Documents folder. This was a simple way to get around issues with Apple's sandboxing in newer versions of macOS.  Also, when I installed flashbake in macOS all three dependencies that are specified in setup.py had to be installed manually. 

I will document the Mac issues in the wiki once this PR is accepted.

### CODE REVIEW

**Comment by jpenney** [comment]
FYI: If I remember correctly the Scrivener plugin worked for the Windows version of Scrivener as well (since it’s the same file format). There might be some extra stuff that worked only on Mac but it should have fallen back nicely and worked on any platform you happened to store your Scrivener files on.  

Since it’s still the only format I use flashbake for, I guess I’ll have to find time to look into it. That said, I’m stuck on an ancient Mac with with ancient Scrivener, so I’ll have to see if I can get some sample files from the latest Mac/Windows versions.

**Comment by ianpaul** [comment]
Your help would be most welcome @jpenney . On the instructions in the wiki, it says you need to go to _Options/Preferences > General_ and check the option _Enable Subversion/CVS-compatible saving (slower)_." That setting doesn't exist in Windows in Scrivener 1.9 or 3. I'll try and run the plugin and see if it just works. Maybe we'll get lucky. If it does need an overhaul, though, it would be really great if you could take care of it. I can also send you a test file saved with Scrivener 3 if you need it.

**Comment by ianpaul** [comment]
Jason, I tried the Scrivener plugin and it doesn't work. I'm getting an invalid module error, which usually means there's a deprecated import in there somewhere. If you have time to figure this out that would be fantastic. Also note that my .flashbake file needed to look like this. 

**plugins:**flashbake.plugins.scrivener:ScrivenerFile,**plugins:**flashbake.plugins.scrivener:ScrivenerWordcountFile,**plugins:**flashbake.plugins.scrivener:ScrivenerWordcountMessage

The wiki doesn't have the first `plugins:` for each one, which meant Flashbake wasn't recognizing them at all in my tests. I also noticed that on line 44 it's looking for `.scriv` and not `.scrivx`, but if your Scrivener isn't using scrivx send me the plugin once you've got it running and I'll test it on my system.

**Comment by jpenney** [comment]
My recollection about the alternate saving format, is that predates the support for iOS/Mac/Windows syncing, and that the current versions always work this way (but I could be wrong).  On Mac (on my version) the .scrivx file lives inside the .scriv bundle, and so it's included.

**Comment by ianpaul** [comment]
I see. So you have to have the .scriv bundle inside a git director and then add the .scriv bundle to your hotfiles? Windows treats the scriv bundle as a regular folder so I just initialized Git in there, which is why I switched to .scrivx. Though it didn't really matter as the plugin wouldn't run.

**Comment by jpenney** [comment]
Yeah, you need to add the `.scriv` folder to hotfiles, everything is based on that as a starting point (from the terminal and git/flashbake's POV `.scriv` is a folder even on Mac, it's just from the GUI it's treated differently).

**Comment by ianpaul** [comment]
Does anybody know anything about AppleScript @cmdln or @jpenney ? The `current_track.scpt` file is now calling Music instead of iTunes since that's what Catalina has. Is there a way in AppleScript to test if iTunes or Music is installed and then execute accordingly? I couldn't find a satisfactory answer online.

**Review by cmdln — APPROVED** [review]
This looks fantastic, @ianpaul--thank you!

**Comment by ianpaul** [comment]
Awesome, I'm thrilled this worked out. Getting this port done was a long-standing goal.

**Pull request merged**
